class Job:
    def __init__(self):
        self.job_id = "123"
        self.item_id = "default_item_id"
        self.store_id = ""
        self.main_img_src = "main_img_src"
        self.tao_key = "tao_key"
        self.keyword = "keyword"
        self.compare_img_src = "compare_img_src"
        self.sku = "sku"
        self.pay_amount = ""
        self.task_amount = ""
        self.chat_questions = ""
        self.comments = ""
        self.comment_img_src = "comment_img_src"
        self.salary = ""
        self.status = "init"
